name: Build and lint code
description: Action that installs dependencies, builds and lints the code
branding:
  icon: 'check'
  color: 'green'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: c-hive/gha-yarn-cache@v2
    - name: Install modules
      run: yarn
    - name: Build code
      run: yarn build
    - name: Lint code
      run: yarn lint
